### ISSUE TITLE
Crash Occured when Eric Join Server

### ISSUE THREAD

**Issue by Grifthegnome** [Grifthegnome/OutlawMod#119]
Running on 64 bit Windows 10.0.22621.0 with 65275 MB RAM
Game Version: v1.19.3 (Stable)
1/30/2024 9:50:06 AM: Critical error occurred in the following mod: trailmod@1.0.2
Loaded Mods: bedrespawner@1.0.0, butchering@1.1.0, millwright@1.1.3, primitivesurvival@3.4.5, sortablestorage@2.2.1, game@1.19.3, weaponpackalphaunoff@1.5.0, animationmanagerlib@0.5.0, brutalstory@1.0.0, carryon@1.7.4, commonlib@2.3.2, earlychiseling@1.0.1, farmlanddropssoil@1.4.0, hudclock@3.4.0, sailboat@1.2.6, medievalexpansion@3.13.1, meteoricexpansion@1.2.5, natsachievements@1.0.0, nobells@1.0.0, nodrifters@1.0.0, outlawmod@1.2.1, petai@2.2.3, rivers@2.0.0, stepup@1.2.0, tentbag@1.0.2, trailmod@1.0.2, creative@1.19.3, vsquest@1.2.0, survival@1.19.3, vsvillage@0.9.1, metalrecovery@0.1.19-pre.1, bullseye@2.5.2, fsmlib@0.2.2-pre.1, maltiezbows@1.0.1, playercorpse@1.9.0, simplewinddirection@1.0.2, wolftaming@2.0.2, maltiezfirearms@0.4.0-pre.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at TrailMod.OverrideOnEntityCollide.OnEntityCollideOverride(Block __instance, IWorldAccessor world, Entity entity, BlockPos pos, BlockFacing facing, Vec3d collideSpeed, Boolean isImpact)
   at Vintagestory.API.Common.Block.OnEntityCollide_Patch1(Block this, IWorldAccessor world, Entity entity, BlockPos pos, BlockFacing facing, Vec3d collideSpeed, Boolean isImpact)
   at Vintagestory.API.MathTools.CollisionTester.ApplyTerrainCollision(Entity entity, EntityPos entitypos, Single dtFac, Vec3d& outposition, Single stepHeight, Single YExtra) in VintagestoryApi\Math\CollisionTester.cs:line 175
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.DisplaceWithBlockCollision(EntityPos pos, EntityControls controls, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 343
   at Vintagestory.GameContent.EntityBehaviorControlledPhysics.TickEntityPhysics(EntityPos pos, EntityControls controls, Single dt) in VSEssentials\Entity\Behavior\BehaviorControlledPhysics.cs:line 226
   at Vintagestory.GameContent.EntityBehaviorPlayerPhysics.onPhysicsTick(Single deltaTime) in VSEssentials\Entity\Behavior\BehaviorPlayerPhysics.cs:line 108
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Grifthegnome** [comment]
Logic was running on client and not checking for validity of entity that triggered collision, which is a problem in the case of a connecting player.
