### ISSUE TITLE
Client Entity Ledger Crash: Picking Gold Bar Up Out of Mold (May be fixed in newer version of Expanded Tasks)

### ISSUE THREAD

**Issue by Grifthegnome** [Grifthegnome/OutlawMod#133]
4.2.2024 03:37:51 [Server Event] Player EdUb3 got removed. Reason: Threw an exception at the server
4.2.2024 03:37:51 [Server Error] Exception: Object reference not set to an instance of an object.
   at ExpandedAiTasks.Managers.EntityLedger.AddEntityItemToLedger(Entity entity)
   at ExpandedAiTasks.AfterInitializedOverride.OverrideAfterInitialized(Entity __instance, Boolean onFirstSpawn)
   at Vintagestory.API.Common.Entities.Entity.AfterInitialized_Patch1(Entity this, Boolean onFirstSpawn)
   at Vintagestory.Server.ServerMain.SpawnEntity(Entity entity, EntityProperties type) in VintagestoryLib\Server\ServerMain.cs:line 2330
   at Vintagestory.Server.ServerMain.SpawnItemEntity(ItemStack itemstack, Vec3d position, Vec3d velocity) in VintagestoryLib\Server\ServerMain.cs:line 2230
   at Vintagestory.GameContent.BlockEntityIngotMold.TryTakeIngot_Patch1(BlockEntityIngotMold this, IPlayer byPlayer, Vec3d hitPosition)
   at Vintagestory.GameContent.BlockEntityIngotMold.OnPlayerInteract(IPlayer byPlayer, BlockFacing onFace, Vec3d hitPosition) in VSSurvivalMod\BlockEntity\BEIngotMold.cs:line 200
   at Vintagestory.GameContent.BlockIngotMold.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Block\BlockIngotMold.cs:line 195
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 426
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138

**Comment by Grifthegnome** [comment]
5.2.2024 20:55:11 [Server Error] Exception: Object reference not set to an instance of an object.
   at ExpandedAiTasks.Managers.EntityLedger.AddEntityItemToLedger(Entity entity)
   at ExpandedAiTasks.AfterInitializedOverride.OverrideAfterInitialized(Entity __instance, Boolean onFirstSpawn)
   at Vintagestory.API.Common.Entities.Entity.AfterInitialized_Patch1(Entity this, Boolean onFirstSpawn)
   at Vintagestory.Server.ServerMain.SpawnEntity(Entity entity, EntityProperties type) in VintagestoryLib\Server\ServerMain.cs:line 2330
   at Vintagestory.Server.ServerMain.SpawnItemEntity(ItemStack itemstack, Vec3d position, Vec3d velocity) in VintagestoryLib\Server\ServerMain.cs:line 2230
   at Vintagestory.GameContent.BlockEntityForge.OnPlayerInteract(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\BlockEntity\BEForge.cs:line 203
   at Vintagestory.GameContent.BlockForge.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Block\BlockForge.cs:line 180
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockInteract(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 426
   at Vintagestory.Server.ServerSystemInventory.HandleHandInteraction(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\Inventory.cs:line 252
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138

**Comment by Grifthegnome** [comment]
This occurred when eric picked up a bar off the forge. He kept crashing trying to pick up his inventory.

**Comment by Grifthegnome** [comment]
We have attempted to address this with a local change, monitor this.
