### ISSUE TITLE
Null Object Reference Causing Extreme Server Lag.

### ISSUE THREAD

**Issue by Grifthegnome** [Grifthegnome/OutlawMod#44]
11.1.2024 12:32:56 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 124
   at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881

**Comment by Grifthegnome** [comment]
This may not be related to our mod, it seems like it was related to one of the debug tool player chat message server events we were using to check performance.

**Comment by Grifthegnome** [comment]
I have not been able to repro this, but it seems like it was not related to the mod. Will see if anyone gets this in live.

**Comment by Grifthegnome** [comment]
We haven't had this again in many hours of playing the game multiplayer nor has anything been reported by the community.
