### ISSUE TITLE
Investigate Client Crash

### ISSUE THREAD

**Issue by Grifthegnome** [Grifthegnome/OutlawMod#68]
System.Exception: Max joint cap of 36 reached, needs to be at least 43. In clientsettings.json, please try increasing the "maxAnimatedElements": setting to 46.  This works for most GPUs.  Otherwise you might need to disable the creature.
   at Vintagestory.API.Common.Animation.GenerateAllFrames(ShapeElement[] rootElements, Dictionary`2 jointsById, Boolean recursive) in VintagestoryApi\Common\Model\Animation\Animation.cs:line 97
   at Vintagestory.API.Common.ClientAnimator.AnimNowActive(RunningAnimation anim, AnimationMetaData animData) in VintagestoryApi\Common\Model\Animation\ClientAnimator.cs:line 225
   at Vintagestory.API.Common.AnimatorBase.OnFrame(Dictionary`2 activeAnimationsByAnimCode, Single dt) in VintagestoryApi\Common\Model\Animation\AnimatorBase.cs:line 115
   at Vintagestory.API.Common.AnimationManager.OnClientFrame(Single dt) in VintagestoryApi\Common\Model\Animation\AnimationManager.cs:line 347
   at Vintagestory.Client.NoObf.SystemRenderEntities.OnBeforeRender(Single dt) in VintagestoryLib\Client\Systems\Render\RenderEntities.cs:line 49
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 808
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 724
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
Crash written to file at "C:\Users\devin\AppData\Roaming\VintagestoryData\Logs\client-crash.txt"

**Comment by Grifthegnome** [comment]
This is likely related to Devin upgrading from an older version of vintage story and having his ClientSettings.Json settings for maxAnimatedElements set to a value lower than the amount set by the game. Keep an eye on this, close if it doesn't repro.

**Comment by Grifthegnome** [comment]
I will re-open this if it occurs again.
