### ISSUE TITLE
Client Crashes When Player Attacks a Straw Dummy

### ISSUE THREAD

**Issue by Grifthegnome** [Grifthegnome/OutlawMod#75]
19.1.2024 00:10:10 [Server Error] Exception: Object reference not set to an instance of an object.
   at ExpandedAiTasks.AiUtility.IsInCombat(Entity ent)
   at OutlawMod.OnEntityReceiveDamageOverride.OverrideOnEntityReceiveDamage(EntityBehaviorHealth __instance, DamageSource damage
Source, Single& damage)
   at Vintagestory.GameContent.EntityBehaviorHealth.OnEntityReceiveDamage_Patch1(EntityBehaviorHealth this, DamageSource damageS
ource, Single& damage)
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage) in VintagestoryApi\Common\
Entity\Entity.cs:line 806
   at Vintagestory.API.Common.EntityAgent.ReceiveDamage_Patch1(EntityAgent this, DamageSource damageSource, Single damage)
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mo
de) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 285
   at Vintagestory.GameContent.EntityStrawDummy.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractM
ode mode) in VSSurvivalMod\Entities\EntityStrawDummy.cs:line 12
   at Vintagestory.Server.ServerSystemEntitySimulation.HandleEntityInteraction(Packet_Client packet, ConnectedClient client)
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\S
erverMainNetworking.cs:line 138

**Comment by Grifthegnome** [comment]
AiUtility.IsInCombat was assuming that all EnitityAgents would have the EntityBehaviorTaskAi behavior. We now check and early out false if this is not true.
