### ISSUE TITLE
All clients crash when they receive damage packet from server. (Might be related to blocks damaging player)

### ISSUE THREAD

**Issue by Grifthegnome** [Grifthegnome/OutlawMod#80]
Running on 64 bit Windows 10.0.22621.0 with 65275 MB RAM
Game Version: v1.19.1 (Stable)
1/21/2024 6:33:29 PM: Critical error occurred in the following mod: brutalstory@1.0.0
Loaded Mods: primitivesurvival@3.4.5, game@1.19.1, weaponpackalphaunoff@1.5.0, brutalstory@1.0.0, hudclock@3.4.0, sailboat@1.2.6, nobells@1.0.0, nodrifters@1.0.0, outlawmod@1.2.1, rivers@1.1.2, stepup@1.2.0, th3dungeon@0.2.1-rc.1, trailmod@1.0.0, creative@1.19.1, survival@1.19.1, simplewinddirection@1.0.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at brutalstory.src.BloodFX.Bleed(EntityAgent agent, DamageSource damageSource, Single damage)
   at Vintagestory.Client.NoObf.NetworkChannel.<>c__DisplayClass12_0`1.<SetMessageHandler>b__0(Packet_CustomPacket p) in VintagestoryLib\Client\API\NetworkChannel.cs:line 74
   at Vintagestory.Client.NoObf.NetworkAPI.HandleCustomPacket(Packet_Server packet) in VintagestoryLib\Client\API\NetworkAPI.cs:line 95
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 769
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 675
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 650
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Grifthegnome** [comment]
All crashed occurred while the player was digging and blocks were collapsing on them.

**Comment by Grifthegnome** [comment]
Has not occurred since I checked in the fix for EntityAgents with no health attribute playing damage.

**Comment by Grifthegnome** [comment]
I think this was related to a dirt block hitting a carcass entity. When it crashed the final time, Eric was running the old version of the BrutalStory client and I was running the new version with the Entity Agent Health Check fixes. He crashed and I didn't making me think that was the issue.

**Comment by Grifthegnome** [comment]
Has not occurred since fixes went in.
